name: Build SMM

on:
  push:
    tags:
    - "v*"
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_dist:
    name: Build dist
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build dist from source
        run: |
          python -m pip install build
          python -m build --sdist
          
      - name: Place dist in artifacts folder
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ build_dist ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: "Release ${{ github.ref }}"
          files: |
            ./dist/**/*

      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          python -m twine upload dist/**/* --verbose --skip-existing