name: Build Package

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_dist:
    name: Build dist
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build dist from source
        run: |
          python -m pip install build
          python -m build --sdist
          
      - name: Place dist in artifacts folder
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build and twine
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build --wheel

      - name: List built files
        run: ls -lh dist
      
      - name: Place dist in artifacts folder
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz